<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cardatabase" nsURI="http://www.example.org/cardatabase" nsPrefix="cardatabase">
  <eSubpackages name="newPackage1">
    <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//newPackage1/Person"/>
    <eClassifiers xsi:type="ecore:EClass" name="Person" instanceClassName="person"/>
    <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//newPackage1/Person"/>
  </eSubpackages>
</ecore:EPackage>
